//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmPrincipal.COperador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operador", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Operador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_opField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_admissãoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_nascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoguinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefone_celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefone_fixoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Venda[] VendasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_op {
            get {
                return this.Cod_opField;
            }
            set {
                if ((this.Cod_opField.Equals(value) != true)) {
                    this.Cod_opField = value;
                    this.RaisePropertyChanged("Cod_op");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_admissão {
            get {
                return this.Data_admissãoField;
            }
            set {
                if ((this.Data_admissãoField.Equals(value) != true)) {
                    this.Data_admissãoField = value;
                    this.RaisePropertyChanged("Data_admissão");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_nascimento {
            get {
                return this.Data_nascimentoField;
            }
            set {
                if ((this.Data_nascimentoField.Equals(value) != true)) {
                    this.Data_nascimentoField = value;
                    this.RaisePropertyChanged("Data_nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Loguin {
            get {
                return this.LoguinField;
            }
            set {
                if ((object.ReferenceEquals(this.LoguinField, value) != true)) {
                    this.LoguinField = value;
                    this.RaisePropertyChanged("Loguin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone_celular {
            get {
                return this.Telefone_celularField;
            }
            set {
                if ((object.ReferenceEquals(this.Telefone_celularField, value) != true)) {
                    this.Telefone_celularField = value;
                    this.RaisePropertyChanged("Telefone_celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone_fixo {
            get {
                return this.Telefone_fixoField;
            }
            set {
                if ((object.ReferenceEquals(this.Telefone_fixoField, value) != true)) {
                    this.Telefone_fixoField = value;
                    this.RaisePropertyChanged("Telefone_fixo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Venda[] Vendas {
            get {
                return this.VendasField;
            }
            set {
                if ((object.ReferenceEquals(this.VendasField, value) != true)) {
                    this.VendasField = value;
                    this.RaisePropertyChanged("Vendas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venda", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Venda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_opField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Itens_venda Itens_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Nota_fiscal[] Nota_fiscalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Operador OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Valor_total_vendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_op {
            get {
                return this.Cod_opField;
            }
            set {
                if ((this.Cod_opField.Equals(value) != true)) {
                    this.Cod_opField = value;
                    this.RaisePropertyChanged("Cod_op");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_venda {
            get {
                return this.Cod_vendaField;
            }
            set {
                if ((this.Cod_vendaField.Equals(value) != true)) {
                    this.Cod_vendaField = value;
                    this.RaisePropertyChanged("Cod_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_venda {
            get {
                return this.Data_vendaField;
            }
            set {
                if ((this.Data_vendaField.Equals(value) != true)) {
                    this.Data_vendaField = value;
                    this.RaisePropertyChanged("Data_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Itens_venda Itens_venda {
            get {
                return this.Itens_vendaField;
            }
            set {
                if ((object.ReferenceEquals(this.Itens_vendaField, value) != true)) {
                    this.Itens_vendaField = value;
                    this.RaisePropertyChanged("Itens_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Nota_fiscal[] Nota_fiscals {
            get {
                return this.Nota_fiscalsField;
            }
            set {
                if ((object.ReferenceEquals(this.Nota_fiscalsField, value) != true)) {
                    this.Nota_fiscalsField = value;
                    this.RaisePropertyChanged("Nota_fiscals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Operador Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor_total_venda {
            get {
                return this.Valor_total_vendaField;
            }
            set {
                if ((this.Valor_total_vendaField.Equals(value) != true)) {
                    this.Valor_total_vendaField = value;
                    this.RaisePropertyChanged("Valor_total_venda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Itens_venda", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Itens_venda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Itens_nota[] Itens_notasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Valor_total_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Valor_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Venda VendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_produto {
            get {
                return this.Cod_produtoField;
            }
            set {
                if ((this.Cod_produtoField.Equals(value) != true)) {
                    this.Cod_produtoField = value;
                    this.RaisePropertyChanged("Cod_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_venda {
            get {
                return this.Cod_vendaField;
            }
            set {
                if ((this.Cod_vendaField.Equals(value) != true)) {
                    this.Cod_vendaField = value;
                    this.RaisePropertyChanged("Cod_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Itens_nota[] Itens_notas {
            get {
                return this.Itens_notasField;
            }
            set {
                if ((object.ReferenceEquals(this.Itens_notasField, value) != true)) {
                    this.Itens_notasField = value;
                    this.RaisePropertyChanged("Itens_notas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor_total_produto {
            get {
                return this.Valor_total_produtoField;
            }
            set {
                if ((this.Valor_total_produtoField.Equals(value) != true)) {
                    this.Valor_total_produtoField = value;
                    this.RaisePropertyChanged("Valor_total_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor_venda {
            get {
                return this.Valor_vendaField;
            }
            set {
                if ((this.Valor_vendaField.Equals(value) != true)) {
                    this.Valor_vendaField = value;
                    this.RaisePropertyChanged("Valor_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Venda Venda {
            get {
                return this.VendaField;
            }
            set {
                if ((object.ReferenceEquals(this.VendaField, value) != true)) {
                    this.VendaField = value;
                    this.RaisePropertyChanged("Venda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nota_fiscal", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Nota_fiscal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_emissão_notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Itens_nota[] Itens_notasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Itens_nota[] Itens_notas1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Venda VendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_nota {
            get {
                return this.Cod_notaField;
            }
            set {
                if ((this.Cod_notaField.Equals(value) != true)) {
                    this.Cod_notaField = value;
                    this.RaisePropertyChanged("Cod_nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_venda {
            get {
                return this.Cod_vendaField;
            }
            set {
                if ((this.Cod_vendaField.Equals(value) != true)) {
                    this.Cod_vendaField = value;
                    this.RaisePropertyChanged("Cod_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_emissão_nota {
            get {
                return this.Data_emissão_notaField;
            }
            set {
                if ((this.Data_emissão_notaField.Equals(value) != true)) {
                    this.Data_emissão_notaField = value;
                    this.RaisePropertyChanged("Data_emissão_nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Itens_nota[] Itens_notas {
            get {
                return this.Itens_notasField;
            }
            set {
                if ((object.ReferenceEquals(this.Itens_notasField, value) != true)) {
                    this.Itens_notasField = value;
                    this.RaisePropertyChanged("Itens_notas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Itens_nota[] Itens_notas1 {
            get {
                return this.Itens_notas1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Itens_notas1Field, value) != true)) {
                    this.Itens_notas1Field = value;
                    this.RaisePropertyChanged("Itens_notas1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Venda Venda {
            get {
                return this.VendaField;
            }
            set {
                if ((object.ReferenceEquals(this.VendaField, value) != true)) {
                    this.VendaField = value;
                    this.RaisePropertyChanged("Venda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_loteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_entradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Itens_venda[] Itens_vendasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Lote LoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Tipo_produto Tipo_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Valor_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Valor_vendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_lote {
            get {
                return this.Cod_loteField;
            }
            set {
                if ((this.Cod_loteField.Equals(value) != true)) {
                    this.Cod_loteField = value;
                    this.RaisePropertyChanged("Cod_lote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_produto {
            get {
                return this.Cod_produtoField;
            }
            set {
                if ((this.Cod_produtoField.Equals(value) != true)) {
                    this.Cod_produtoField = value;
                    this.RaisePropertyChanged("Cod_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_tipo {
            get {
                return this.Cod_tipoField;
            }
            set {
                if ((this.Cod_tipoField.Equals(value) != true)) {
                    this.Cod_tipoField = value;
                    this.RaisePropertyChanged("Cod_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_entrada {
            get {
                return this.Data_entradaField;
            }
            set {
                if ((this.Data_entradaField.Equals(value) != true)) {
                    this.Data_entradaField = value;
                    this.RaisePropertyChanged("Data_entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Itens_venda[] Itens_vendas {
            get {
                return this.Itens_vendasField;
            }
            set {
                if ((object.ReferenceEquals(this.Itens_vendasField, value) != true)) {
                    this.Itens_vendasField = value;
                    this.RaisePropertyChanged("Itens_vendas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Lote Lote {
            get {
                return this.LoteField;
            }
            set {
                if ((object.ReferenceEquals(this.LoteField, value) != true)) {
                    this.LoteField = value;
                    this.RaisePropertyChanged("Lote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((object.ReferenceEquals(this.PesoField, value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Tipo_produto Tipo_produto {
            get {
                return this.Tipo_produtoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_produtoField, value) != true)) {
                    this.Tipo_produtoField = value;
                    this.RaisePropertyChanged("Tipo_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Valor_compra {
            get {
                return this.Valor_compraField;
            }
            set {
                if ((this.Valor_compraField.Equals(value) != true)) {
                    this.Valor_compraField = value;
                    this.RaisePropertyChanged("Valor_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Valor_venda {
            get {
                return this.Valor_vendaField;
            }
            set {
                if ((this.Valor_vendaField.Equals(value) != true)) {
                    this.Valor_vendaField = value;
                    this.RaisePropertyChanged("Valor_venda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Itens_nota", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Itens_nota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Itens_venda Itens_vendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Nota_fiscal Nota_fiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Nota_fiscal Nota_fiscal1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_nota {
            get {
                return this.Cod_notaField;
            }
            set {
                if ((this.Cod_notaField.Equals(value) != true)) {
                    this.Cod_notaField = value;
                    this.RaisePropertyChanged("Cod_nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_venda {
            get {
                return this.Cod_vendaField;
            }
            set {
                if ((this.Cod_vendaField.Equals(value) != true)) {
                    this.Cod_vendaField = value;
                    this.RaisePropertyChanged("Cod_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Itens_venda Itens_venda {
            get {
                return this.Itens_vendaField;
            }
            set {
                if ((object.ReferenceEquals(this.Itens_vendaField, value) != true)) {
                    this.Itens_vendaField = value;
                    this.RaisePropertyChanged("Itens_venda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Nota_fiscal Nota_fiscal {
            get {
                return this.Nota_fiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.Nota_fiscalField, value) != true)) {
                    this.Nota_fiscalField = value;
                    this.RaisePropertyChanged("Nota_fiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Nota_fiscal Nota_fiscal1 {
            get {
                return this.Nota_fiscal1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nota_fiscal1Field, value) != true)) {
                    this.Nota_fiscal1Field = value;
                    this.RaisePropertyChanged("Nota_fiscal1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lote", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Lote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_fornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_loteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Data_entradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Fornecedor FornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Prazo_validadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Produto[] ProdutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Tipo_produto Tipo_produtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Valor_total_loteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_fornecedor {
            get {
                return this.Cod_fornecedorField;
            }
            set {
                if ((this.Cod_fornecedorField.Equals(value) != true)) {
                    this.Cod_fornecedorField = value;
                    this.RaisePropertyChanged("Cod_fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_lote {
            get {
                return this.Cod_loteField;
            }
            set {
                if ((this.Cod_loteField.Equals(value) != true)) {
                    this.Cod_loteField = value;
                    this.RaisePropertyChanged("Cod_lote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_tipo {
            get {
                return this.Cod_tipoField;
            }
            set {
                if ((this.Cod_tipoField.Equals(value) != true)) {
                    this.Cod_tipoField = value;
                    this.RaisePropertyChanged("Cod_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data_entrada {
            get {
                return this.Data_entradaField;
            }
            set {
                if ((this.Data_entradaField.Equals(value) != true)) {
                    this.Data_entradaField = value;
                    this.RaisePropertyChanged("Data_entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Fornecedor Fornecedor {
            get {
                return this.FornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorField, value) != true)) {
                    this.FornecedorField = value;
                    this.RaisePropertyChanged("Fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prazo_validade {
            get {
                return this.Prazo_validadeField;
            }
            set {
                if ((object.ReferenceEquals(this.Prazo_validadeField, value) != true)) {
                    this.Prazo_validadeField = value;
                    this.RaisePropertyChanged("Prazo_validade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Produto[] Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Tipo_produto Tipo_produto {
            get {
                return this.Tipo_produtoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_produtoField, value) != true)) {
                    this.Tipo_produtoField = value;
                    this.RaisePropertyChanged("Tipo_produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor_total_lote {
            get {
                return this.Valor_total_loteField;
            }
            set {
                if ((this.Valor_total_loteField.Equals(value) != true)) {
                    this.Valor_total_loteField = value;
                    this.RaisePropertyChanged("Valor_total_lote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo_produto", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Tipo_produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriçãoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Lote[] LotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Produto[] ProdutosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_tipo {
            get {
                return this.Cod_tipoField;
            }
            set {
                if ((this.Cod_tipoField.Equals(value) != true)) {
                    this.Cod_tipoField = value;
                    this.RaisePropertyChanged("Cod_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrição {
            get {
                return this.DescriçãoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriçãoField, value) != true)) {
                    this.DescriçãoField = value;
                    this.RaisePropertyChanged("Descrição");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Lote[] Lotes {
            get {
                return this.LotesField;
            }
            set {
                if ((object.ReferenceEquals(this.LotesField, value) != true)) {
                    this.LotesField = value;
                    this.RaisePropertyChanged("Lotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Produto[] Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fornecedor", Namespace="http://schemas.datacontract.org/2004/07/Mercearia.Model")]
    [System.SerializableAttribute()]
    public partial class Fornecedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_fornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Insc_estadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private frmPrincipal.COperador.Lote[] LotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nome_fantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_fixoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_fornecedor {
            get {
                return this.Cod_fornecedorField;
            }
            set {
                if ((this.Cod_fornecedorField.Equals(value) != true)) {
                    this.Cod_fornecedorField = value;
                    this.RaisePropertyChanged("Cod_fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insc_estadual {
            get {
                return this.Insc_estadualField;
            }
            set {
                if ((object.ReferenceEquals(this.Insc_estadualField, value) != true)) {
                    this.Insc_estadualField = value;
                    this.RaisePropertyChanged("Insc_estadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public frmPrincipal.COperador.Lote[] Lotes {
            get {
                return this.LotesField;
            }
            set {
                if ((object.ReferenceEquals(this.LotesField, value) != true)) {
                    this.LotesField = value;
                    this.RaisePropertyChanged("Lotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome_fantasia {
            get {
                return this.Nome_fantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nome_fantasiaField, value) != true)) {
                    this.Nome_fantasiaField = value;
                    this.RaisePropertyChanged("Nome_fantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_celular {
            get {
                return this.Tel_celularField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_celularField, value) != true)) {
                    this.Tel_celularField = value;
                    this.RaisePropertyChanged("Tel_celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_fixo {
            get {
                return this.Tel_fixoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_fixoField, value) != true)) {
                    this.Tel_fixoField = value;
                    this.RaisePropertyChanged("Tel_fixo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="COperador.ICOperador")]
    public interface ICOperador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Incluir", ReplyAction="http://tempuri.org/ICOperador/IncluirResponse")]
        void Incluir(frmPrincipal.COperador.Operador oOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Incluir", ReplyAction="http://tempuri.org/ICOperador/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(frmPrincipal.COperador.Operador oOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Alterar", ReplyAction="http://tempuri.org/ICOperador/AlterarResponse")]
        void Alterar(frmPrincipal.COperador.Operador oOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Alterar", ReplyAction="http://tempuri.org/ICOperador/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(frmPrincipal.COperador.Operador oOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Excluir", ReplyAction="http://tempuri.org/ICOperador/ExcluirResponse")]
        void Excluir(frmPrincipal.COperador.Operador oOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Excluir", ReplyAction="http://tempuri.org/ICOperador/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(frmPrincipal.COperador.Operador oOperador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Selecionar", ReplyAction="http://tempuri.org/ICOperador/SelecionarResponse")]
        frmPrincipal.COperador.Operador Selecionar(int Cod_op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/Selecionar", ReplyAction="http://tempuri.org/ICOperador/SelecionarResponse")]
        System.Threading.Tasks.Task<frmPrincipal.COperador.Operador> SelecionarAsync(int Cod_op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/SelecionarTodos", ReplyAction="http://tempuri.org/ICOperador/SelecionarTodosResponse")]
        frmPrincipal.COperador.Operador[] SelecionarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOperador/SelecionarTodos", ReplyAction="http://tempuri.org/ICOperador/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<frmPrincipal.COperador.Operador[]> SelecionarTodosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICOperadorChannel : frmPrincipal.COperador.ICOperador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COperadorClient : System.ServiceModel.ClientBase<frmPrincipal.COperador.ICOperador>, frmPrincipal.COperador.ICOperador {
        
        public COperadorClient() {
        }
        
        public COperadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COperadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COperadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COperadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(frmPrincipal.COperador.Operador oOperador) {
            base.Channel.Incluir(oOperador);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(frmPrincipal.COperador.Operador oOperador) {
            return base.Channel.IncluirAsync(oOperador);
        }
        
        public void Alterar(frmPrincipal.COperador.Operador oOperador) {
            base.Channel.Alterar(oOperador);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(frmPrincipal.COperador.Operador oOperador) {
            return base.Channel.AlterarAsync(oOperador);
        }
        
        public void Excluir(frmPrincipal.COperador.Operador oOperador) {
            base.Channel.Excluir(oOperador);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(frmPrincipal.COperador.Operador oOperador) {
            return base.Channel.ExcluirAsync(oOperador);
        }
        
        public frmPrincipal.COperador.Operador Selecionar(int Cod_op) {
            return base.Channel.Selecionar(Cod_op);
        }
        
        public System.Threading.Tasks.Task<frmPrincipal.COperador.Operador> SelecionarAsync(int Cod_op) {
            return base.Channel.SelecionarAsync(Cod_op);
        }
        
        public frmPrincipal.COperador.Operador[] SelecionarTodos() {
            return base.Channel.SelecionarTodos();
        }
        
        public System.Threading.Tasks.Task<frmPrincipal.COperador.Operador[]> SelecionarTodosAsync() {
            return base.Channel.SelecionarTodosAsync();
        }
    }
}
